name: Verify ds-stack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ds-stack config
        run: docker-compose -f "ds-stack/docker-compose.yml" config
      - name: ds-stack up
        run: docker-compose -f "ds-stack/docker-compose.yml" up -d --build
      - name: ds-stack down
        run: docker-compose -f "ds-stack/docker-compose.yml" down
      - name: minio-sts config
        run: docker-compose -f "minio-sts/docker-compose.yml" config
      - name: minio-sts up
        run: docker-compose -f "minio-sts/docker-compose.yml" up -d --build
      - name: minio-sts down
        run: docker-compose -f "minio-sts/docker-compose.yml" down