name: Verify docker-compose.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show the config
        run: docker-compose config
      - name: Run
        run: docker-compose up -d --build