version: "3.9"

services:
  jupyterlab:
    container_name: jupyterab
    image: jupyter/minimal-notebook:ubuntu-20.04
    entrypoint:
      - start-notebook.sh
      - --ServerApp.password=${JUPYTERLAB_PASSWORD-''}
      - --ServerApp.token=${JUPYTERLAB_TOKEN-''}
    restart: always
    ports:
      - "${JUPYTERLAB_PORT-8888}:8888"
    environment:
      JUPYTER_ENABLE_LAB: "true"
      MLFLOW_TRACKING_URI: "http://localhost:${MLFLOW_PORT-5000}"
    volumes:
      - ./data_jupyter:/data

  mlflow-artifact:
    container_name: mlflow-artifact
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    command: server /data
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY-minio123}
    volumes:
      - ./data_minio:/data

  mlflow-backend:
    container_name: mlflow-backend
    image: postgres:9.6.22-alpine
    restart: always
    expose:
      - "${MLFLOW_DB_PORT-5432}"
    environment:
      POSTGRES_USER: ${MLFLOW_DB_USERNAME-mlflow}
      POSTGRES_PASSWORD: ${MLFLOW_DB_PASSWORD-mlflow}
      POSTGRES_DB: ${MLFLOW_DB_DATABASE-mlflow}
    volumes:
      - ./data_postgres:/var/lib/mysql

  mlflow:
    container_name: mlflow
    build:
      context: ./mlflow
    ports:
      - ${MLFLOW_PORT-5000}:${MLFLOW_PORT-5000}
    depends_on:
      - mlflow-backend
      - mlflow-artifact
    environment: 
      MLFLOW_PORT: ${MLFLOW_PORT-5000}
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY-minio}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY-minio123}
      MLFLOW_S3_ENDPOINT_URL: s3://mlflow:9000/
      MLFLOW_DB_DIALECT: postgresql
      MLFLOW_DB_USERNAME: ${MLFLOW_DB_USERNAME-mlflow}
      MLFLOW_DB_PASSWORD: ${MLFLOW_DB_PASSWORD-mlflow}
      MLFLOW_DB_HOST: mlflow-backend
      MLFLOW_DB_PORT: ${MLFLOW_DB_PORT-5432}
      MLFLOW_DB_DATABASE: ${MLFLOW_DB_DATABASE-mlflow}

  dataiku:
    container_name: dataiku
    profiles:
    - dataiku
    build:
      context: ./dataiku
    ports:
      - 11000:11000
    
volumes:
  data_jupyter:
    driver: local
  data_postgres:
    driver: local
  data_minio:
    driver: local
